config/routes.rb
Getitright::Application.routes.draw do

  resources :tasks
  resources :check_lists

  get  'checklists', to: 'check_list_definitions#index', as: :checklists
  post 'check_list_definitions/:id/start', to: 'check_list_definitions#start', as: :start_check_list_definitions

  resources :task_definitions
  resources :check_list_definitions

  devise_for :users,
    controllers: {
      registrations: "registrations",
      omniauth_callbacks: "authentications"
    }

  root 'check_list_definitions#index'

end

app/models/task_definition.rb
class TaskDefinition < ActiveRecord::Base
  belongs_to :check_list_definition
  has_many :tasks, -> { order :step }
  validates_presence_of [:text, :step]
end

app/controllers/task_definitions_controller.rb
class TaskDefinitionsController < ApplicationController
  before_action :set_task_definition, only: [:show, :edit, :update, :destroy]

  def index
    @task_definitions = TaskDefinition.all
  end

  def show
  end

  def new
    @task_definition = TaskDefinition.new
  end

  def edit
  end

  def create
    @task_definition = TaskDefinition.new(task_definition_params)

    respond_to do |format|
      if @task_definition.save
        format.html { redirect_to @task_definition, notice: 'Task definition was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task_definition }
      else
        format.html { render action: 'new' }
        format.json { render json: @task_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @task_definition.update(task_definition_params)
        format.html { redirect_to @task_definition, notice: 'Task definition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @task_definition.destroy
    respond_to do |format|
      format.html { redirect_to task_definitions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_definition
      @task_definition = TaskDefinition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_definition_params
      params.require(:task_definition).permit(:check_list_definition_id, :text, :step)
    end
end

app/views/task_definitions/_form.html.erb
<%= form_for(@task_definition) do |f| %>
  <% if @task_definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_definition.errors.count, "error") %> prohibited this task_definition from being saved:</h2>

      <ul>
      <% @task_definition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :check_list_definition %><br>
    <%= f.text_field :check_list_definition %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>

app/views/task_definitions/edit.html.erb
<h1>Editing task_definition</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_definition %> |
<%= link_to 'Back', task_definitions_path %>

app/views/task_definitions/index.html.erb
<h1>Listing task_definitions</h1>

<table>
  <thead>
    <tr>
      <th>Check list definition</th>
      <th>Text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @task_definitions.each do |task_definition| %>
      <tr>
        <td><%= task_definition.check_list_definition %></td>
        <td><%= task_definition.text %></td>
        <td><%= link_to 'Show', task_definition %></td>
        <td><%= link_to 'Edit', edit_task_definition_path(task_definition) %></td>
        <td><%= link_to 'Destroy', task_definition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task definition', new_task_definition_path %>

app/views/task_definitions/new.html.erb
<h1>New task definition</h1>

<%= render 'form' %>

<%= link_to 'Back', task_definitions_path %>

app/views/task_definitions/new.js.erb
var taskStep = $('.task-input').length;
var taskInput = '<br /><input type="text" name="check_list_definition[task_definitions_attributes][' +
  taskStep + '][text]" id="check_list_definition_task_definitions_attributes_' + 
  taskStep + '_text" class="task-input">' +
  '<input type="hidden" value="' + taskStep +
  '" name="check_list_definition[task_definitions_attributes][' + taskStep +
  '][step]" id="check_list_definition_task_definitions_attributes_' + taskStep + '_step"> ';

$('#addTaskBtn').before(taskInput);

app/views/task_definitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Check list definition:</strong>
  <%= @task_definition.check_list_definition %>
</p>

<p>
  <strong>Text:</strong>
  <%= @task_definition.text %>
</p>

<%= link_to 'Edit', edit_task_definition_path(@task_definition) %> |
<%= link_to 'Back', task_definitions_path %>