config/routes.rb
Getitright::Application.routes.draw do

  resources :tasks
  resources :check_lists

  get  'checklists', to: 'check_list_definitions#index', as: :checklists
  post 'check_list_definitions/:id/start', to: 'check_list_definitions#start', as: :start_check_list_definitions

  resources :task_definitions
  resources :check_list_definitions

  devise_for :users,
    controllers: {
      registrations: "registrations",
      omniauth_callbacks: "authentications"
    }

  root 'check_list_definitions#index'

end

app/models/check_list_definition.rb
class CheckListDefinition < ActiveRecord::Base
  has_many :task_definitions, -> { order :step }
  accepts_nested_attributes_for :task_definitions
  belongs_to :user
  has_many :check_lists
  validates_presence_of :name

  scope :ordered, -> { order(:created_at).includes(:user) }
end

app/controllers/check_list_definitions_controller.rb
class CheckListDefinitionsController < ApplicationController
  before_action :set_check_list_definition, only: [:show, :edit, :update, :destroy, :start]

  def index
    if user_signed_in?
      check_lists = CheckListDefinition.ordered
      @check_list_definitions = current_user.check_list_definitions.ordered
      @other_public_check_list_definitions = CheckListDefinition.ordered.where("user_id <> ?", current_user)
    else
      @check_list_definitions = CheckListDefinition.ordered
    end
  end

  def show
  end

  def new
    @check_list_definition = current_user.check_list_definitions.build
    @check_list_definition.task_definitions.build
  end

  def edit
  end

  def create
    @check_list_definition = current_user.check_list_definitions.build(check_list_definition_params)

    respond_to do |format|
      if @check_list_definition.save
        format.html { redirect_to check_list_definitions_path, notice: 'Check list definition was successfully created.' }
        format.json { render action: 'show', status: :created, location: @check_list_definition }
      else
        format.html { render action: 'new' }
        format.json { render json: @check_list_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @check_list_definition.update(check_list_definition_params)
        format.html { redirect_to check_list_definitions_path, notice: 'Check list definition was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @check_list_definition.errors, status: :unprocessable_entity }
      end
    end
  end

  # fork la checklist pour le nouvel utilisateur
  def start
    @check_list = check_list_factory.create(@check_list_definition, current_user)
    respond_to do |format|
      format.html { redirect_to edit_check_list_url(@check_list) }
      format.json { head :no_content }
    end
  end

  def destroy
    @check_list_definition.destroy
    respond_to do |format|
      format.html { redirect_to check_list_definitions_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_check_list_definition
    @check_list_definition = CheckListDefinition.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def check_list_definition_params
    params.require(:check_list_definition)
          .permit(:user_id,
                  :name,
                  :description,
                  task_definitions_attributes: [:id, :text, :step]
                 )
  end

  def check_list_factory
    @check_list_factory ||= CheckListFactory.new
  end 

end

app/helpers/check_list_definitions_helper.rb
module CheckListDefinitionsHelper
end

app/views/check_list_definitions/_check_list_definition.html.erb
<div class="col-sm-6 col-md-4 check-list-definition">
  <div><strong><%= link_to check_list_definition.name, check_list_definition %></strong> by <%= check_list_definition.user %></div>
  <% unless check_list_definition.description.blank? %>
    <p><%= check_list_definition.description %></p>
  <% end %>

  <% if user_signed_in? %>
    <%= link_to start_check_list_definitions_path(check_list_definition),
      method: :post, class: "btn btn-primary" do %>
      <span class="glyphicon glyphicon-play"></span> Start
    <% end %>
  <% else %>
    <%= link_to '#', class: "btn btn-primary", 'data-toggle' => "modal", 'data-target' => "#signinModal" do %>
      <span class="glyphicon glyphicon-play"></span> Start
    <% end %>
  <% end %>
</div>

app/views/check_list_definitions/_form.html.erb
<%= form_for(@check_list_definition) do |f| %>
  <% if @check_list_definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@check_list_definition.errors.count, "error") %> prohibited this check_list_definition from being saved:</h2>

      <ul>
      <% @check_list_definition.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, size: 80 %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 4, cols: 80 %>
  </div>

  <div>
    Tasks
    <div class="taskInputs">
      <%= f.fields_for :task_definitions do |task_definition| %>
        <%= render :partial => "task_definition_fields",
          :locals => { :f => task_definition }
        %>
      <% end %>
      <%= link_to "+", new_task_definition_path,
        remote: true, class: "btn btn-default btn-xs",
        id: "addTaskBtn"
      %>
    </div>
  </div>
<br/>
  <div class="actions">
    <%= f.submit 'OK', class: "btn btn-primary" %>
    <%= link_to 'Back', check_list_definitions_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/check_list_definitions/_task_definition_fields.html.erb
<%= f.text_field :text, size:80, class: "task-input" %>
<%= f.hidden_field :step, :value => f.options[:child_index] %>

app/views/check_list_definitions/edit.html.erb
<h1>Editing check list</h1>

<%= render 'form' %>

app/views/check_list_definitions/index.html.erb
<% if user_signed_in? %>
  <h1>My checklists</h1>
  <div class="row">
    <%= render @check_list_definitions %>
  </div>

  <h1>Public checklists</h1>
  <div class="row">
    <%= render @other_public_check_list_definitions %>
  </div>
<% else %>
  <div class="row">
    <%= render @check_list_definitions %>
  </div>
<% end %>
</div>

app/views/check_list_definitions/new.html.erb
<h1>New Check List</h1>

<%= render 'form' %>

app/views/check_list_definitions/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<h1><%= @check_list_definition.name %> <small>by <%= @check_list_definition.user %></small></h1>
<p>
  <%= @check_list_definition.description %>
</p>

<p>
  <ul class="list-unstyled">
    <% @check_list_definition.task_definitions.each do |task_definition| %>
      <li class="task-definition">
        <span class="glyphicon glyphicon-ok"></span> <%= task_definition.text %>
      </li>
    <% end %>
  </ul>
</p>
<div class="actions">
  <!--%= link_to 'Back', check_list_definitions_path, class: "btn btn-primary" %> |
  <!--%= link_to 'Edit', edit_check_list_definition_path(@check_list_definition), class: "btn btn-primary" %-->
  <% if user_signed_in? %>
    <%= link_to start_check_list_definitions_path(@check_list_definition),
      method: :post, class: "btn btn-primary" do %>
      <span class="glyphicon glyphicon-play"></span> Start
    <% end %>
  <% else %>
    <%= link_to '#', class: "btn btn-primary", 'data-toggle' => "modal", 'data-target' => "#signinModal" do %>
      <span class="glyphicon glyphicon-play"></span> Start
    <% end %>
  <% end %>
</div>