config/routes.rb
Getitright::Application.routes.draw do

  resources :tasks
  resources :check_lists

  get  'checklists', to: 'check_list_definitions#index', as: :checklists
  post 'check_list_definitions/:id/start', to: 'check_list_definitions#start', as: :start_check_list_definitions

  resources :task_definitions
  resources :check_list_definitions

  devise_for :users,
    controllers: {
      registrations: "registrations",
      omniauth_callbacks: "authentications"
    }

  root 'check_list_definitions#index'

end

app/views/layouts/_flash.html.erb
<% if notice %>
    <div class="alert alert-info">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <%= notice %>
    </div>
<% end %>
<% if alert %>
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <%= alert %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="text-muted credit">&copy; Get It Right 2013 | 
      <%= link_to 'About', '#' %> | 
      <%= link_to 'Contact', '#' %>
    </p>
  </div>
</div>

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(
['siteTracker._setAccount', 'UA-45800862-1'],
['siteTracker._trackPageview']);

(function() {
var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ga);
})();
</script>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('logo.png', alt: "Get it right"), root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <% if user_signed_in? %>
        <ul class="nav navbar-nav">
          <li><%= link_to 'Create Checklist', new_check_list_definition_path %></li><li>
          <li><%= link_to 'My Started Checklists', check_lists_path(status: "started") %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li>
          <%= link_to "#", class: "navbar-avatar" do %>
            <%= image_tag current_user.avatar %>
            &nbsp;<%= current_user.name %>
          <% end %>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete, data: { confirm: "Are you sure you want to sign out?" } %> </li>
            </ul>
          </li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Sign in / sign up", '#', 'data-toggle' => "modal", 'data-target' => "#signinModal" %></li>
        </ul>
      <% end %>
  </div>
</div>
</div>

<!-- Sign in form -->
<% unless user_signed_in? %>
  <div class="modal fade" id="signinModal" tabindex="-1" role="dialog" aria-labelledby="signinModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="signinModalLabel">Sign in</h4>
        </div>
        <div class="modal-body">
          <%= render 'shared/signin_links' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Get it right</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon', :type => 'image/ico' %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->

  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </div>
  <%= render 'layouts/footer' %>

  <%= render 'layouts/google_analytics' if Rails.env.production? %>
</body>
</html>